/**
 * 
 */
package com.tikal.cacao.model;

/**
 * @author Tikal
 *
 */
public enum RegimenContratacion {
	SUELDOS_Y_SALARIOS,
	JUBILADOS,
	PENSIONADOS,
	ASIMILADOS_A_SALARIOS__MIEMBROS_DE_LAS_SOCIEDADES_COOPERATIVAS_DE_PRODUCCION,
	ASIMILADOS_A_SALARIOS_INTEGRANTES_DE_SOCIEDADES_Y_ASOCIACIONES_CIVILES,
	ASIMILADOS_A_SALARIOS_MIEMBROS_DE_CONSEJOS_DIRECTIVOS_DE_VIGILANCIA_CONSULTIVOS_HONORARIOS_A_ADMINISTRADORES_COMISARIOS_Y_GERENTES_GENERALES,
	ASIMILADOS_A_SALARIOS_ACTIVIDAD_EMPRESARIAL_COMISIONISTAS,
	ASIMILADOS_A_SALARIOS_HONORARIOS_ASIMILADOS_A_SALARIOS,
	ASIMILADOS_A_SALARIOS_INGRESOS_ACCIONES_O_TITULOS_VALOR
}
