/**
 * 
 */
package com.tikal.cacao.model;

/**
 * @author Tikal
 *
 */
public enum TipoDeduccion {
	SEGURIDAD_SOCIAL,
	ISR,
	APORTACIONES_A_RETIRO_CESANTIA_EN_EDAD_AVANZADA_Y_VEJEZ,
	OTROS,
	APORTACIONES_A_FONDO_DE_VIVIENDA,
	DESCUENTO_POR_INCAPACIDAD,
	PENSION_ALIMENTICIA,
	RENTA,
	PRESTAMOS_PROVENIENTES_DEL_FONDO_NACIONAL_DE_LA_VIVIENDA_PARA_LOS_TRABAJADORES,
	PAGO_POR_CREDITO_DE_VIVIENDA,
	PAGO_DE_ABONOS_INFONACOT,
	ANTICIPO_DE_SALARIOS,
	PAGOS_HECHOS_CON_EXCESO_AL_TRABAJADOR,
	ERRORES,
	PERDIDAS,
	AVERIAS,
	ADQUISICION_DE_ARTICULOS_PRODUCIDOS_POR_LA_EMPRESA_O_ESTABLECIMIENTO,
	CUOTAS_PARA_LA_CONSTITUCION_Y_FOMENTO_DE_SOCIEDADES_COOPERATIVAS_Y_DE_CAJAS_DE_AHORRO,
	CUOTAS_SINDICALES,
	AUSENCIA,
	CUOTAS_OBRERO_PATRONALES
	
	
}
