/**
 * 
 */
package com.tikal.cacao.model;

/**
 * @author Tikal
 *
 */
public enum TipoPercepcion {
	SUELDOS_SALARIOS_RAYAS_JORNALES,
	GRATIFICACION_ANUAL_AGUINALDO,
	PARTICIPACION_DE_LOS_TRABAJADORES_EN_LAS_UTILIDADES_PTU, 
	REEMBOLSO_GASTOS_MEDICOS_DENTALES_Y_HOSPITALARIOS,
	FONDO_DE_AHORRO,
	CAJA_DE_AHORRO,
	CONTRIBUCIONES_A_CARGO_DEL_TRABAJADOR_PAGADAS_POR_EL_PATRON,
	PREMIOS_POR_PUNTUALIDAD,
	PRIMA_DE_SEGURO_DE_VIDA,
	SEGURO_DE_GASTOS_MEDICOS_MAYORES,
	CUOTAS_SINDICALES_PAGADAS_POR_EL_PATRON,
	SUBSIDIOS_POR_INCAPACIDAD,
	BECAS_PARA_TRABAJADORES_Y_O_HIJOS,
	OTROS,
	SUBSIDIOS_PARA_EL_EMPLEO,
	HORAS_EXTRA,
	PRIMA_DOMINICAL,
	PRIMA_VACACIONAL,
	PRIMA_POR_ANTIGUEDAD,
	PAGOS_POR_SEPARACION,
	SEGURO_DE_RETIRO,
	INDEMNIZACIONES,
	REEMBOLSO_POR_FUNERAL,
	CUOTAS_DE_SEGURIDAD_SOCIAL_PAGADAS_POR_EL_PATRON,
	COMISIONES,
	VALES_DE_DESPENSA,
	VALES_DE_RESTAURANTE,
	VALES_DE_GASOLINA,
	VALES_DE_ROPA,
	AYUDA_PARA_RENTA,
	AYUDA_PARA_ARTICULOS_ESCOLARES,
	AYUDA_PARA_ANTEOJOS,
	AYUDA_PARA_TRANSPORTE,
	AYUDA_PARA_GASTOS_DE_FUNERAL,
	OTROS_INGRESOS_POR_SALARIOS,
	JUBILACIONES_PENSIONES_O_HABERES_DE_RETIRO,
	INGRESO_PAGADO_POR_ENTIDADES_FEDERATIVAS_MUNICIPIOS_O_DEMARCACIONES_TERRITORIALES_DE_LA_CIUDAD_DE_MEXICO_ORGANISMOS_AUTONOMOS_Y_ENTIDADES_PARAESTATALES_Y_PARAMUNICIPALES_CON_INGRESOS_PROPIOS,
	INGRESO_PAGADO_POR_ENTIDADES_FEDERATIVAS_MUNICIPIOS_O_DEMARCACIONES_TERRITORIALES_DE_LA_CIUDAD_DE_MEXICO_ORGANISMOS_AUTONOMOS_Y_ENTIDADES_PARAESTATALES_Y_PARAMUNICIPALES_CON_INGRESOS_FEDERAÑES,
	INGRESO_PAGADO_POR_ENTIDADES_FEDERATIVAS_MUNICIPIOS_O_DEMARCACIONES_TERRITORIALES_DE_LA_CIUDAD_DE_MEXICO_ORGANISMOS_AUTONOMOS_Y_ENTIDADES_PARAESTATALES_Y_PARAMUNICIPALES_CON_INGRESOS_PROPIOS_Y_FEDERALES
	
}
